### ISSUE TITLE
enableUser() method returns 400 status error

### ISSUE THREAD

**Issue by asjustis** [Backendless/JS-SDK#189]
Hi, 

Using the latest (6.1.5) Backendless JS version, for some reason, when running `const response = await Backendless.UserService.enableUser(objectId);` method, I get a weird `Operation allowed only for BL logic.` error. 
Is this a bug?

```
error: Error: Operation allowed only for BL logic. 
code: 3054
headers: {content-length: "77", content-type: "application/json"}
message: "Operation allowed only for BL logic."
status: 400
stack: "Error: Operation allowed only for BL logic.
```

If it helps, I also add the stacktrace I got:

```
backendless.js:1194 PUT https://api.backendless.com/F2FE78BB-5D08-44FE-B074-6E7C29B49B03/7A6587CC-100A-4CAC-A7E2-3DBD30C6F0C1/users/EEA5EE59-B554-4749-9DF5-AA9EA415BEC8/status 400 (Bad Request)
sendRequest @ backendless.js:1194
sendXmlHttpRequest @ backendless.js:1158
Request.send @ backendless.js:1629
send @ backendless.js:1572
then @ backendless.js:1596
load (async)
sendRequest @ backendless.js:1163
sendXmlHttpRequest @ backendless.js:1158
Request.send @ backendless.js:1629
send @ backendless.js:1572
then @ backendless.js:1596
_callee3$ @ backendless.js:15562
tryCatch @ backendless.js:11239
invoke @ backendless.js:11468
prototype.<computed> @ backendless.js:11291
asyncGeneratorStep @ backendless.js:216
_next @ backendless.js:238
(anonymous) @ backendless.js:245
(anonymous) @ backendless.js:234
find @ backendless.js:15578
getUser @ auth.js:106
init @ EmailSetup.js:41
(anonymous) @ EmailSetup.js:53
commitHookEffectList @ react-dom.development.js:19986
commitPassiveHookEffects @ react-dom.development.js:20016
callCallback @ react-dom.development.js:347
__trace__ @ inline-script-content.js:138
invokeGuardedCallbackDev @ react-dom.development.js:397
invokeGuardedCallback @ react-dom.development.js:454
flushPassiveEffectsImpl @ react-dom.development.js:22868
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushPassiveEffects @ react-dom.development.js:22841
renderRoot @ react-dom.development.js:21801
runRootCallback @ react-dom.development.js:21554
(anonymous) @ react-dom.development.js:11353
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushSyncCallbackQueueImpl @ react-dom.development.js:11349
flushSyncCallbackQueue @ react-dom.development.js:11338
unbatchedUpdates @ react-dom.development.js:21692
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24962
render @ react-dom.development.js:25042
(anonymous) @ index.js:45
./src/index.js @ index.js:73
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ FaceGeniusIntro.mp4:1
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
Show 21 more frames
console-breadcrumbs.js:33 rresp {error: Error: Operation allowed only for BL logic.
    at new ResponseError (https://localhost:3000/static…}error: Error: Operation allowed only for BL logic.
    at new ResponseError (https://localhost:3000/static/js/0.chunk.js:191588:130)
    at checkStatus (https://localhost:3000/static/js/0.chunk.js:191782:23)__proto__: Object```

**Comment by Valodya** [comment]
Hello, 

`Operation allowed only for BL logic` - means that you can run this API only by using the `CloudCode API Key` which is used inside the Business Logic automatically. 

Regards, Vlad

**Comment by asjustis** [comment]
The what... So when I use this method in my website (using JS SDK) to manually confirm the user, I need to switch to the CloudCode Api key instead of JS Api key?

**Comment by Valodya** [comment]
this is unsecured, I would recommend you do not share your CloudCode API Key on the client side 

P.S., please use our [support forum](https://support.backendless.com) or our [slack channel](https://slack.backendless.com/)   to get more information

**Comment by asjustis** [comment]
Hi @Valodya , just to follow-up, I am now calling this method through the Business Logic, but it doesn't seem to return any kind of response - whether it succeeded, or if the user was already enabled. Is there any way to know this?
